spring.application.name=HiFreshApp
# Anslutning till PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/hifresh_db
spring.datasource.username=postgres
spring.datasource.password=Appleman6254!

# JPA / Hibernate inställningar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
